services:
  app:
    build:
      context: .
      target: prod
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      NEON_LOCAL: 'false'
    ports:
      - '3000:3000'
    restart: unless-stopped
    command: >
      sh -c "npx drizzle-kit migrate && npm start"
